# docker-compose.yml
version: '3.8'
services:
  search-visualizer-service:
    build: ..
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI
      - MONGO_DB_NAME
      - FEATURES_COLLECTION
      - PROCESSING_QUEUE
      - RABBITMQ_HOST
      - PRODUCT_UPDATES_QUEUE
      - SCHEDULE_QUEUE
      - AUTH_SERVICE_URL
      - FLASK_APP_PORT

networks:
  default:
