# docker-compose.yml
version: '3.8'
services:
  search-visualizer-service:
    build: .
    ports:
      - "${FLASK_APP_PORT}:${FLASK_APP_PORT}"
    environment:
      - MONGO_URI
      - MONGO_DB_NAME
      - FEATURES_COLLECTION
      - PROCESSING_QUEUE
      - RABBITMQ_HOST
      - PRODUCT_UPDATES_QUEUE
      - SCHEDULE_QUEUE
      - AUTH_SERVICE_URL
      - FLASK_APP_PORT
    depends_on:
      - mongo
      - rabbitmq

#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
#
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "15672:15672"
#      - "5672:5672"

networks:
  default:
